// Auto-generated Component Registry
// Generated at: 2025-08-19T19:29:14.965Z
// Total components: 128

import {
  ComponentRegistry,
  ComponentCategory,
} from "../types/component-registry";

export const COMPONENT_REGISTRY: ComponentRegistry = {
  "providers-query-provider": {
    id: "providers-query-provider",
    name: "QueryProvider",
    filePath: "/providers/QueryProvider.tsx",
    startLine: 11,
    endLine: 30,
    category: ComponentCategory.UI,
    description: "QueryProvider component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.870Z",
    exports: [],
  },
  "components-theme-switch": {
    id: "components-theme-switch",
    name: "ThemeSwitch",
    filePath: "/components/theme-switch.tsx",
    startLine: 17,
    endLine: 81,
    category: ComponentCategory.UI,
    description: "ThemeSwitch component",
    dependencies: ["className", "classNames"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.874Z",
    exports: [],
  },
  "components-navbar": {
    id: "components-navbar",
    name: "Navbar",
    filePath: "/components/navbar.tsx",
    startLine: 23,
    endLine: 99,
    category: ComponentCategory.NAVIGATION,
    description: "Navbar component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.877Z",
    exports: [],
  },
  "components-navbar-user-menu": {
    id: "components-navbar-user-menu",
    name: "NavbarUserMenu",
    filePath: "/components/navbar-user-menu.tsx",
    startLine: 16,
    endLine: 97,
    category: ComponentCategory.NAVIGATION,
    description: "NavbarUserMenu component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.878Z",
    exports: [],
  },
  "components-logo": {
    id: "components-logo",
    name: "Logo",
    filePath: "/components/icons.tsx",
    startLine: 5,
    endLine: 27,
    category: ComponentCategory.UI,
    description: "Logo component",
    dependencies: ["size", "width", "height"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.881Z",
    exports: [],
  },
  "components-discord-icon": {
    id: "components-discord-icon",
    name: "DiscordIcon",
    filePath: "/components/icons.tsx",
    startLine: 29,
    endLine: 48,
    category: ComponentCategory.UI,
    description: "DiscordIcon component",
    dependencies: ["size", "width", "height"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.881Z",
    exports: [],
  },
  "components-twitter-icon": {
    id: "components-twitter-icon",
    name: "TwitterIcon",
    filePath: "/components/icons.tsx",
    startLine: 50,
    endLine: 69,
    category: ComponentCategory.UI,
    description: "TwitterIcon component",
    dependencies: ["size", "width", "height"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.881Z",
    exports: [],
  },
  "components-github-icon": {
    id: "components-github-icon",
    name: "GithubIcon",
    filePath: "/components/icons.tsx",
    startLine: 71,
    endLine: 92,
    category: ComponentCategory.UI,
    description: "GithubIcon component",
    dependencies: ["size", "width", "height"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.881Z",
    exports: [],
  },
  "components-moon-filled-icon": {
    id: "components-moon-filled-icon",
    name: "MoonFilledIcon",
    filePath: "/components/icons.tsx",
    startLine: 94,
    endLine: 114,
    category: ComponentCategory.UI,
    description: "MoonFilledIcon component",
    dependencies: ["size", "width", "height"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.881Z",
    exports: [],
  },
  "components-sun-filled-icon": {
    id: "components-sun-filled-icon",
    name: "SunFilledIcon",
    filePath: "/components/icons.tsx",
    startLine: 116,
    endLine: 136,
    category: ComponentCategory.UI,
    description: "SunFilledIcon component",
    dependencies: ["size", "width", "height"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.881Z",
    exports: [],
  },
  "components-heart-filled-icon": {
    id: "components-heart-filled-icon",
    name: "HeartFilledIcon",
    filePath: "/components/icons.tsx",
    startLine: 138,
    endLine: 161,
    category: ComponentCategory.UI,
    description: "HeartFilledIcon component",
    dependencies: ["size", "width", "height"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.881Z",
    exports: [],
  },
  "components-search-icon": {
    id: "components-search-icon",
    name: "SearchIcon",
    filePath: "/components/icons.tsx",
    startLine: 163,
    endLine: 189,
    category: ComponentCategory.UI,
    description: "SearchIcon component",
    dependencies: ["props"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.881Z",
    exports: [],
  },
  "components-counter": {
    id: "components-counter",
    name: "Counter",
    filePath: "/components/counter.tsx",
    startLine: 6,
    endLine: 14,
    category: ComponentCategory.UI,
    description: "Counter component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.881Z",
    exports: [],
  },
  "components-navbar-skeleton": {
    id: "components-navbar-skeleton",
    name: "NavbarSkeleton",
    filePath: "/components/LayoutWrapper.tsx",
    startLine: 13,
    endLine: 17,
    category: ComponentCategory.LAYOUT,
    description: "NavbarSkeleton component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.882Z",
    exports: [],
  },
  "components-layout-wrapper": {
    id: "components-layout-wrapper",
    name: "LayoutWrapper",
    filePath: "/components/LayoutWrapper.tsx",
    startLine: 19,
    endLine: 52,
    category: ComponentCategory.LAYOUT,
    description: "LayoutWrapper component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.882Z",
    exports: [],
  },
  "components-herit-logo": {
    id: "components-herit-logo",
    name: "HeritLogo",
    filePath: "/components/HeritLogo.tsx",
    startLine: 10,
    endLine: 24,
    category: ComponentCategory.UI,
    description: "HeritLogo component",
    dependencies: ["size", "width", "height", "className"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.882Z",
    exports: [],
  },
  "components-acme-icon": {
    id: "components-acme-icon",
    name: "AcmeIcon",
    filePath: "/components/AcmeIcon.tsx",
    startLine: 5,
    endLine: 25,
    category: ComponentCategory.UI,
    description: "AcmeIcon component",
    dependencies: ["size", "width", "height"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.883Z",
    exports: [],
  },
  "app-providers": {
    id: "app-providers",
    name: "Providers",
    filePath: "/app/providers.tsx",
    startLine: 25,
    endLine: 35,
    category: ComponentCategory.UI,
    description: "Providers component",
    dependencies: ["children", "themeProps"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.884Z",
    exports: [],
  },
  "app-home-page": {
    id: "app-home-page",
    name: "HomePage",
    filePath: "/app/page.tsx",
    startLine: 6,
    endLine: 8,
    category: ComponentCategory.UI,
    description: "HomePage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.885Z",
    exports: [],
  },
  "app-root-layout": {
    id: "app-root-layout",
    name: "RootLayout",
    filePath: "/app/layout.tsx",
    startLine: 48,
    endLine: 94,
    category: ComponentCategory.LAYOUT,
    description: "RootLayout component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.886Z",
    exports: [],
  },
  "app-error": {
    id: "app-error",
    name: "Error",
    filePath: "/app/error.tsx",
    startLine: 5,
    endLine: 31,
    category: ComponentCategory.FEEDBACK,
    description: "Error component",
    dependencies: ["error", "reset"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.887Z",
    exports: [],
  },
  "app-home-page-client": {
    id: "app-home-page-client",
    name: "HomePageClient",
    filePath: "/app/HomePageClient.tsx",
    startLine: 7,
    endLine: 48,
    category: ComponentCategory.UI,
    description: "HomePageClient component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.888Z",
    exports: [],
  },
  "ui-vertical-steps": {
    id: "ui-vertical-steps",
    name: "VerticalSteps",
    filePath: "/components/ui/VerticalSteps.tsx",
    startLine: 46,
    endLine: 170,
    category: ComponentCategory.UI,
    description: "VerticalSteps component",
    dependencies: [
      "steps",
      "defaultStep",
      "onStepChange",
      "currentStep",
      "hideProgressBars",
      "stepClassName",
      "className",
    ],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.890Z",
    exports: [],
  },
  "documents-document-upload-zone": {
    id: "documents-document-upload-zone",
    name: "DocumentUploadZone",
    filePath: "/components/documents/DocumentUploadZone.tsx",
    startLine: 49,
    endLine: 467,
    category: ComponentCategory.INPUT,
    description: "DocumentUploadZone component",
    dependencies: [
      "assetId",
      "assetType",
      "onUploadComplete",
      "onError",
      "suggestedCategory",
      "suggestedType",
      "maxFiles",
    ],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.896Z",
    exports: [],
  },
  "documents-document-manager": {
    id: "documents-document-manager",
    name: "DocumentManager",
    filePath: "/components/documents/DocumentManager.tsx",
    startLine: 53,
    endLine: 457,
    category: ComponentCategory.BUSINESS,
    description: "DocumentManager component",
    dependencies: ["assetId", "assetType", "className"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.901Z",
    exports: [],
  },
  "dev-wrapped-component": {
    id: "dev-wrapped-component",
    name: "WrappedComponent",
    filePath: "/components/dev/withComponentMetadata.tsx",
    startLine: 14,
    endLine: 29,
    category: ComponentCategory.UI,
    description: "WrappedComponent component",
    dependencies: ["props"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.904Z",
    exports: [],
  },
  "dev-component-wrapper": {
    id: "dev-component-wrapper",
    name: "ComponentWrapper",
    filePath: "/components/dev/withComponentMetadata.tsx",
    startLine: 38,
    endLine: 63,
    category: ComponentCategory.LAYOUT,
    description: "ComponentWrapper component",
    dependencies: ["componentId", "metadata", "children", "className"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.904Z",
    exports: [],
  },
  "visual-dev-mode-panel": {
    id: "visual-dev-mode-panel",
    name: "VisualDevModePanel",
    filePath: "/components/dev/VisualDevMode.tsx",
    startLine: 12,
    endLine: 233,
    category: ComponentCategory.UI,
    description: "VisualDevModePanel component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.906Z",
    exports: [],
  },
  "dev-component-overlay": {
    id: "dev-component-overlay",
    name: "ComponentOverlay",
    filePath: "/components/dev/ComponentOverlay.tsx",
    startLine: 12,
    endLine: 113,
    category: ComponentCategory.UI,
    description: "ComponentOverlay component",
    dependencies: ["componentId", "metadata", "children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.908Z",
    exports: [],
  },
  "dashboard-layout": {
    id: "dashboard-layout",
    name: "DashboardLayout",
    filePath: "/components/dashboard/DashboardLayout.tsx",
    startLine: 9,
    endLine: 16,
    category: ComponentCategory.LAYOUT,
    description: "DashboardLayout component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.908Z",
    exports: [],
  },
  "auth-protected-route": {
    id: "auth-protected-route",
    name: "ProtectedRoute",
    filePath: "/components/auth/ProtectedRoute.tsx",
    startLine: 14,
    endLine: 57,
    category: ComponentCategory.AUTHENTICATION,
    description: "ProtectedRoute component",
    dependencies: ["children", "requireOnboarding"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.909Z",
    exports: [],
  },
  "auth-login-form": {
    id: "auth-login-form",
    name: "LoginForm",
    filePath: "/components/auth/LoginForm.tsx",
    startLine: 13,
    endLine: 118,
    category: ComponentCategory.INPUT,
    description: "LoginForm component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.909Z",
    exports: [],
  },
  "auth-google-sign-in-button": {
    id: "auth-google-sign-in-button",
    name: "GoogleSignInButton",
    filePath: "/components/auth/GoogleSignInButton.tsx",
    startLine: 10,
    endLine: 34,
    category: ComponentCategory.INPUT,
    description: "GoogleSignInButton component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.910Z",
    exports: [],
  },
  "auth-github-sign-in-button": {
    id: "auth-github-sign-in-button",
    name: "GithubSignInButton",
    filePath: "/components/auth/GithubSignInButton.tsx",
    startLine: 6,
    endLine: 22,
    category: ComponentCategory.INPUT,
    description: "GithubSignInButton component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.910Z",
    exports: [],
  },
  "auth-email-signup-form": {
    id: "auth-email-signup-form",
    name: "EmailSignupForm",
    filePath: "/components/auth/EmailSignupForm.tsx",
    startLine: 9,
    endLine: 168,
    category: ComponentCategory.INPUT,
    description: "EmailSignupForm component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.912Z",
    exports: [],
  },
  "auth-email-login-form": {
    id: "auth-email-login-form",
    name: "EmailLoginForm",
    filePath: "/components/auth/EmailLoginForm.tsx",
    startLine: 9,
    endLine: 97,
    category: ComponentCategory.INPUT,
    description: "EmailLoginForm component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.912Z",
    exports: [],
  },
  "auth-apple-sign-in-button": {
    id: "auth-apple-sign-in-button",
    name: "AppleSignInButton",
    filePath: "/components/auth/AppleSignInButton.tsx",
    startLine: 5,
    endLine: 26,
    category: ComponentCategory.INPUT,
    description: "AppleSignInButton component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.913Z",
    exports: [],
  },
  "pricing-page": {
    id: "pricing-page",
    name: "PricingPage",
    filePath: "/app/pricing/page.tsx",
    startLine: 3,
    endLine: 9,
    category: ComponentCategory.UI,
    description: "PricingPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.914Z",
    exports: [],
  },
  "pricing-layout": {
    id: "pricing-layout",
    name: "PricingLayout",
    filePath: "/app/pricing/layout.tsx",
    startLine: 1,
    endLine: 13,
    category: ComponentCategory.LAYOUT,
    description: "PricingLayout component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.914Z",
    exports: [],
  },
  "docs-page": {
    id: "docs-page",
    name: "DocsPage",
    filePath: "/app/docs/page.tsx",
    startLine: 3,
    endLine: 9,
    category: ComponentCategory.UI,
    description: "DocsPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.914Z",
    exports: [],
  },
  "docs-layout": {
    id: "docs-layout",
    name: "DocsLayout",
    filePath: "/app/docs/layout.tsx",
    startLine: 1,
    endLine: 13,
    category: ComponentCategory.LAYOUT,
    description: "DocsLayout component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.914Z",
    exports: [],
  },
  "blog-page": {
    id: "blog-page",
    name: "BlogPage",
    filePath: "/app/blog/page.tsx",
    startLine: 3,
    endLine: 9,
    category: ComponentCategory.UI,
    description: "BlogPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.915Z",
    exports: [],
  },
  "blog-layout": {
    id: "blog-layout",
    name: "BlogLayout",
    filePath: "/app/blog/layout.tsx",
    startLine: 1,
    endLine: 13,
    category: ComponentCategory.LAYOUT,
    description: "BlogLayout component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.915Z",
    exports: [],
  },
  "about-page": {
    id: "about-page",
    name: "AboutPage",
    filePath: "/app/about/page.tsx",
    startLine: 3,
    endLine: 9,
    category: ComponentCategory.UI,
    description: "AboutPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.915Z",
    exports: [],
  },
  "about-layout": {
    id: "about-layout",
    name: "AboutLayout",
    filePath: "/app/about/layout.tsx",
    startLine: 1,
    endLine: 13,
    category: ComponentCategory.LAYOUT,
    description: "AboutLayout component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.915Z",
    exports: [],
  },
  "(dashboard)-dashboard-layout-wrapper": {
    id: "(dashboard)-dashboard-layout-wrapper",
    name: "DashboardLayoutWrapper",
    filePath: "/app/(dashboard)/layout.tsx",
    startLine: 5,
    endLine: 16,
    category: ComponentCategory.LAYOUT,
    description: "DashboardLayoutWrapper component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.915Z",
    exports: [],
  },
  "(auth)-auth-layout": {
    id: "(auth)-auth-layout",
    name: "AuthLayout",
    filePath: "/app/(auth)/layout.tsx",
    startLine: 1,
    endLine: 7,
    category: ComponentCategory.LAYOUT,
    description: "AuthLayout component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.916Z",
    exports: [],
  },
  "will-page": {
    id: "will-page",
    name: "WillPage",
    filePath: "/app/(dashboard)/will/page.tsx",
    startLine: 7,
    endLine: 11,
    category: ComponentCategory.BUSINESS,
    description: "WillPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.916Z",
    exports: [],
  },
  "will-client": {
    id: "will-client",
    name: "WillClient",
    filePath: "/app/(dashboard)/will/WillClient.tsx",
    startLine: 16,
    endLine: 158,
    category: ComponentCategory.BUSINESS,
    description: "WillClient component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.917Z",
    exports: [],
  },
  "dashboard-page": {
    id: "dashboard-page",
    name: "DashboardPage",
    filePath: "/app/(dashboard)/dashboard/page.tsx",
    startLine: 8,
    endLine: 10,
    category: ComponentCategory.UI,
    description: "DashboardPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.917Z",
    exports: [],
  },
  "dashboard-client": {
    id: "dashboard-client",
    name: "DashboardClient",
    filePath: "/app/(dashboard)/dashboard/DashboardClient.tsx",
    startLine: 41,
    endLine: 386,
    category: ComponentCategory.UI,
    description: "DashboardClient component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.920Z",
    exports: [],
  },
  "beneficiaries-page": {
    id: "beneficiaries-page",
    name: "BeneficiariesPage",
    filePath: "/app/(dashboard)/beneficiaries/page.tsx",
    startLine: 19,
    endLine: 148,
    category: ComponentCategory.UI,
    description: "BeneficiariesPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.926Z",
    exports: [],
  },
  "assets-page": {
    id: "assets-page",
    name: "AssetsPage",
    filePath: "/app/(dashboard)/assets/page.tsx",
    startLine: 42,
    endLine: 396,
    category: ComponentCategory.BUSINESS,
    description: "AssetsPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.929Z",
    exports: [],
  },
  "signup-page": {
    id: "signup-page",
    name: "SignupPage",
    filePath: "/app/(auth)/signup/page.tsx",
    startLine: 23,
    endLine: 333,
    category: ComponentCategory.AUTHENTICATION,
    description: "SignupPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.930Z",
    exports: [],
  },
  "onboarding-page": {
    id: "onboarding-page",
    name: "OnboardingPage",
    filePath: "/app/(auth)/onboarding/page.tsx",
    startLine: 55,
    endLine: 460,
    category: ComponentCategory.AUTHENTICATION,
    description: "OnboardingPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.934Z",
    exports: [],
  },
  "login-page": {
    id: "login-page",
    name: "LoginPage",
    filePath: "/app/(auth)/login/page.tsx",
    startLine: 22,
    endLine: 195,
    category: ComponentCategory.AUTHENTICATION,
    description: "LoginPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.935Z",
    exports: [],
  },
  "highlighting-component-highlighter": {
    id: "highlighting-component-highlighter",
    name: "ComponentHighlighter",
    filePath: "/components/dev/advanced/highlighting/ComponentHighlighter.tsx",
    startLine: 26,
    endLine: 302,
    category: ComponentCategory.UI,
    description: "ComponentHighlighter component",
    dependencies: [
      "enabled",
      "hoverHighlight",
      "clickHighlight",
      "showTooltip",
      "animateOnHover",
      "children",
    ],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.938Z",
    exports: [],
  },
  "highlighting-boundary-overlay": {
    id: "highlighting-boundary-overlay",
    name: "BoundaryOverlay",
    filePath: "/components/dev/advanced/highlighting/BoundaryOverlay.tsx",
    startLine: 33,
    endLine: 238,
    category: ComponentCategory.UI,
    description: "BoundaryOverlay component",
    dependencies: ["enabled", "showLabels", "showDimensions", "opacity"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.940Z",
    exports: [],
  },
  "add-asset-v2page": {
    id: "add-asset-v2page",
    name: "AddAssetV2Page",
    filePath: "/app/(dashboard)/assets/add/page.tsx",
    startLine: 63,
    endLine: 1035,
    category: ComponentCategory.BUSINESS,
    description: "AddAssetV2Page component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.946Z",
    exports: [],
  },
  "components-verification-step": {
    id: "components-verification-step",
    name: "VerificationStep",
    filePath: "/app/(auth)/onboarding/components/VerificationStep.tsx",
    startLine: 30,
    endLine: 429,
    category: ComponentCategory.AUTHENTICATION,
    description: "VerificationStep component",
    dependencies: ["onComplete", "onBack", "loading"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.951Z",
    exports: [],
  },
  "components-signature-step": {
    id: "components-signature-step",
    name: "SignatureStep",
    filePath: "/app/(auth)/onboarding/components/SignatureStep.tsx",
    startLine: 21,
    endLine: 481,
    category: ComponentCategory.AUTHENTICATION,
    description: "SignatureStep component",
    dependencies: [
      "personalInfo",
      "initialSignature",
      "onChange",
      "onComplete",
      "onBack",
      "loading",
    ],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.954Z",
    exports: [],
  },
  "components-signature-stamp": {
    id: "components-signature-stamp",
    name: "SignatureStamp",
    filePath: "/app/(auth)/onboarding/components/SignatureStamp.tsx",
    startLine: 18,
    endLine: 138,
    category: ComponentCategory.AUTHENTICATION,
    description: "SignatureStamp component",
    dependencies: [
      "signature",
      "isSigned",
      "timestamp",
      "onClick",
      "disabled",
      "userName",
      "isLoading",
    ],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.954Z",
    exports: [],
  },
  "components-personal-info-step": {
    id: "components-personal-info-step",
    name: "PersonalInfoStep",
    filePath: "/app/(auth)/onboarding/components/PersonalInfoStep.tsx",
    startLine: 54,
    endLine: 318,
    category: ComponentCategory.AUTHENTICATION,
    description: "PersonalInfoStep component",
    dependencies: [
      "initialData",
      "onChange",
      "onComplete",
      "onBack",
      "loading",
    ],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.956Z",
    exports: [],
  },
  "components-legal-consent-step": {
    id: "components-legal-consent-step",
    name: "LegalConsentStep",
    filePath: "/app/(auth)/onboarding/components/LegalConsentStep.tsx",
    startLine: 65,
    endLine: 490,
    category: ComponentCategory.AUTHENTICATION,
    description: "LegalConsentStep component",
    dependencies: [
      "signature",
      "initialConsents",
      "onChange",
      "onComplete",
      "onBack",
      "loading",
    ],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.959Z",
    exports: [],
  },
  "edit-asset-page": {
    id: "edit-asset-page",
    name: "EditAssetPage",
    filePath: "/app/(dashboard)/assets/[id]/edit/page.tsx",
    startLine: 37,
    endLine: 643,
    category: ComponentCategory.BUSINESS,
    description: "EditAssetPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-19T19:29:14.965Z",
    exports: [],
  },
};

export const getComponentById = (id: string) => COMPONENT_REGISTRY[id];

export const getComponentsByCategory = (category: ComponentCategory) =>
  Object.values(COMPONENT_REGISTRY).filter((c) => c.category === category);

export const getAllComponents = () => Object.values(COMPONENT_REGISTRY);

export const getComponentStats = () => ({
  total: Object.keys(COMPONENT_REGISTRY).length,
  byCategory: Object.values(COMPONENT_REGISTRY).reduce(
    (acc, comp) => {
      acc[comp.category] = (acc[comp.category] || 0) + 1;

      return acc;
    },
    {} as Record<ComponentCategory, number>,
  ),
});
