// Auto-generated Component Registry
// Generated at: 2025-08-23T13:05:03.589Z
// Total components: 134

import {
  ComponentRegistry,
  ComponentCategory,
} from "../types/component-registry";

export const COMPONENT_REGISTRY: ComponentRegistry = {
  "providers-query-provider": {
    id: "providers-query-provider",
    name: "QueryProvider",
    filePath: "/providers/QueryProvider.tsx",
    startLine: 13,
    endLine: 34,
    category: ComponentCategory.UI,
    description: "QueryProvider component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.452Z",
    exports: [],
  },
  "app-providers": {
    id: "app-providers",
    name: "Providers",
    filePath: "/app/providers.tsx",
    startLine: 25,
    endLine: 47,
    category: ComponentCategory.UI,
    description: "Providers component",
    dependencies: ["children", "themeProps"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.455Z",
    exports: [],
  },
  "app-root-layout": {
    id: "app-root-layout",
    name: "RootLayout",
    filePath: "/app/layout.tsx",
    startLine: 48,
    endLine: 98,
    category: ComponentCategory.LAYOUT,
    description: "RootLayout component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.458Z",
    exports: [],
  },
  "app-error": {
    id: "app-error",
    name: "Error",
    filePath: "/app/error.tsx",
    startLine: 5,
    endLine: 31,
    category: ComponentCategory.FEEDBACK,
    description: "Error component",
    dependencies: ["error", "reset"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.460Z",
    exports: [],
  },
  "app-home-page-client": {
    id: "app-home-page-client",
    name: "HomePageClient",
    filePath: "/app/HomePageClient.tsx",
    startLine: 7,
    endLine: 57,
    category: ComponentCategory.UI,
    description: "HomePageClient component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.461Z",
    exports: [],
  },
  "components-theme-switch": {
    id: "components-theme-switch",
    name: "ThemeSwitch",
    filePath: "/components/theme-switch.tsx",
    startLine: 17,
    endLine: 96,
    category: ComponentCategory.UI,
    description: "ThemeSwitch component",
    dependencies: ["className", "classNames"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.463Z",
    exports: [],
  },
  "components-navbar": {
    id: "components-navbar",
    name: "Navbar",
    filePath: "/components/navbar.tsx",
    startLine: 22,
    endLine: 158,
    category: ComponentCategory.NAVIGATION,
    description: "Navbar component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.465Z",
    exports: [],
  },
  "components-navbar-user-menu": {
    id: "components-navbar-user-menu",
    name: "NavbarUserMenu",
    filePath: "/components/navbar-user-menu.tsx",
    startLine: 16,
    endLine: 140,
    category: ComponentCategory.NAVIGATION,
    description: "NavbarUserMenu component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.467Z",
    exports: [],
  },
  "components-logo": {
    id: "components-logo",
    name: "Logo",
    filePath: "/components/icons.tsx",
    startLine: 5,
    endLine: 29,
    category: ComponentCategory.UI,
    description: "Logo component",
    dependencies: ["size", "width", "height"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.469Z",
    exports: [],
  },
  "components-discord-icon": {
    id: "components-discord-icon",
    name: "DiscordIcon",
    filePath: "/components/icons.tsx",
    startLine: 31,
    endLine: 52,
    category: ComponentCategory.UI,
    description: "DiscordIcon component",
    dependencies: ["size", "width", "height"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.469Z",
    exports: [],
  },
  "components-twitter-icon": {
    id: "components-twitter-icon",
    name: "TwitterIcon",
    filePath: "/components/icons.tsx",
    startLine: 54,
    endLine: 75,
    category: ComponentCategory.UI,
    description: "TwitterIcon component",
    dependencies: ["size", "width", "height"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.469Z",
    exports: [],
  },
  "components-github-icon": {
    id: "components-github-icon",
    name: "GithubIcon",
    filePath: "/components/icons.tsx",
    startLine: 77,
    endLine: 100,
    category: ComponentCategory.UI,
    description: "GithubIcon component",
    dependencies: ["size", "width", "height"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.469Z",
    exports: [],
  },
  "components-moon-filled-icon": {
    id: "components-moon-filled-icon",
    name: "MoonFilledIcon",
    filePath: "/components/icons.tsx",
    startLine: 102,
    endLine: 124,
    category: ComponentCategory.UI,
    description: "MoonFilledIcon component",
    dependencies: ["size", "width", "height"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.469Z",
    exports: [],
  },
  "components-sun-filled-icon": {
    id: "components-sun-filled-icon",
    name: "SunFilledIcon",
    filePath: "/components/icons.tsx",
    startLine: 126,
    endLine: 148,
    category: ComponentCategory.UI,
    description: "SunFilledIcon component",
    dependencies: ["size", "width", "height"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.469Z",
    exports: [],
  },
  "components-heart-filled-icon": {
    id: "components-heart-filled-icon",
    name: "HeartFilledIcon",
    filePath: "/components/icons.tsx",
    startLine: 150,
    endLine: 175,
    category: ComponentCategory.UI,
    description: "HeartFilledIcon component",
    dependencies: ["size", "width", "height"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.469Z",
    exports: [],
  },
  "components-search-icon": {
    id: "components-search-icon",
    name: "SearchIcon",
    filePath: "/components/icons.tsx",
    startLine: 177,
    endLine: 205,
    category: ComponentCategory.UI,
    description: "SearchIcon component",
    dependencies: ["props"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.469Z",
    exports: [],
  },
  "components-counter": {
    id: "components-counter",
    name: "Counter",
    filePath: "/components/counter.tsx",
    startLine: 6,
    endLine: 19,
    category: ComponentCategory.UI,
    description: "Counter component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.471Z",
    exports: [],
  },
  "components-navbar-skeleton": {
    id: "components-navbar-skeleton",
    name: "NavbarSkeleton",
    filePath: "/components/LayoutWrapper.tsx",
    startLine: 15,
    endLine: 19,
    category: ComponentCategory.LAYOUT,
    description: "NavbarSkeleton component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.472Z",
    exports: [],
  },
  "components-layout-wrapper": {
    id: "components-layout-wrapper",
    name: "LayoutWrapper",
    filePath: "/components/LayoutWrapper.tsx",
    startLine: 21,
    endLine: 73,
    category: ComponentCategory.LAYOUT,
    description: "LayoutWrapper component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.472Z",
    exports: [],
  },
  "components-herit-logo": {
    id: "components-herit-logo",
    name: "HeritLogo",
    filePath: "/components/HeritLogo.tsx",
    startLine: 10,
    endLine: 26,
    category: ComponentCategory.UI,
    description: "HeritLogo component",
    dependencies: ["size", "width", "height", "className"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.473Z",
    exports: [],
  },
  "components-acme-icon": {
    id: "components-acme-icon",
    name: "AcmeIcon",
    filePath: "/components/AcmeIcon.tsx",
    startLine: 5,
    endLine: 27,
    category: ComponentCategory.UI,
    description: "AcmeIcon component",
    dependencies: ["size", "width", "height"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.475Z",
    exports: [],
  },
  "pricing-page": {
    id: "pricing-page",
    name: "PricingPage",
    filePath: "/app/pricing/page.tsx",
    startLine: 3,
    endLine: 9,
    category: ComponentCategory.UI,
    description: "PricingPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.476Z",
    exports: [],
  },
  "pricing-layout": {
    id: "pricing-layout",
    name: "PricingLayout",
    filePath: "/app/pricing/layout.tsx",
    startLine: 1,
    endLine: 13,
    category: ComponentCategory.LAYOUT,
    description: "PricingLayout component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.476Z",
    exports: [],
  },
  "docs-page": {
    id: "docs-page",
    name: "DocsPage",
    filePath: "/app/docs/page.tsx",
    startLine: 3,
    endLine: 9,
    category: ComponentCategory.UI,
    description: "DocsPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.476Z",
    exports: [],
  },
  "docs-layout": {
    id: "docs-layout",
    name: "DocsLayout",
    filePath: "/app/docs/layout.tsx",
    startLine: 1,
    endLine: 13,
    category: ComponentCategory.LAYOUT,
    description: "DocsLayout component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.477Z",
    exports: [],
  },
  "about-page": {
    id: "about-page",
    name: "AboutPage",
    filePath: "/app/about/page.tsx",
    startLine: 3,
    endLine: 9,
    category: ComponentCategory.UI,
    description: "AboutPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.477Z",
    exports: [],
  },
  "about-layout": {
    id: "about-layout",
    name: "AboutLayout",
    filePath: "/app/about/layout.tsx",
    startLine: 1,
    endLine: 13,
    category: ComponentCategory.LAYOUT,
    description: "AboutLayout component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.477Z",
    exports: [],
  },
  "(dashboard)-dashboard-layout-wrapper": {
    id: "(dashboard)-dashboard-layout-wrapper",
    name: "DashboardLayoutWrapper",
    filePath: "/app/(dashboard)/layout.tsx",
    startLine: 5,
    endLine: 24,
    category: ComponentCategory.LAYOUT,
    description: "DashboardLayoutWrapper component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.477Z",
    exports: [],
  },
  "blog-page": {
    id: "blog-page",
    name: "BlogPage",
    filePath: "/app/blog/page.tsx",
    startLine: 3,
    endLine: 9,
    category: ComponentCategory.UI,
    description: "BlogPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.478Z",
    exports: [],
  },
  "blog-layout": {
    id: "blog-layout",
    name: "BlogLayout",
    filePath: "/app/blog/layout.tsx",
    startLine: 1,
    endLine: 13,
    category: ComponentCategory.LAYOUT,
    description: "BlogLayout component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.478Z",
    exports: [],
  },
  "(auth)-auth-layout": {
    id: "(auth)-auth-layout",
    name: "AuthLayout",
    filePath: "/app/(auth)/layout.tsx",
    startLine: 1,
    endLine: 7,
    category: ComponentCategory.LAYOUT,
    description: "AuthLayout component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.478Z",
    exports: [],
  },
  "ui-vertical-steps": {
    id: "ui-vertical-steps",
    name: "VerticalSteps",
    filePath: "/components/ui/VerticalSteps.tsx",
    startLine: 46,
    endLine: 179,
    category: ComponentCategory.UI,
    description: "VerticalSteps component",
    dependencies: [
      "steps",
      "defaultStep",
      "onStepChange",
      "currentStep",
      "hideProgressBars",
      "stepClassName",
      "className",
    ],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.480Z",
    exports: [],
  },
  "documents-document-upload-zone": {
    id: "documents-document-upload-zone",
    name: "DocumentUploadZone",
    filePath: "/components/documents/DocumentUploadZone.tsx",
    startLine: 49,
    endLine: 593,
    category: ComponentCategory.INPUT,
    description: "DocumentUploadZone component",
    dependencies: [
      "assetId",
      "assetType",
      "onUploadComplete",
      "onError",
      "suggestedCategory",
      "suggestedType",
      "maxFiles",
    ],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.485Z",
    exports: [],
  },
  "documents-document-manager": {
    id: "documents-document-manager",
    name: "DocumentManager",
    filePath: "/components/documents/DocumentManager.tsx",
    startLine: 53,
    endLine: 620,
    category: ComponentCategory.BUSINESS,
    description: "DocumentManager component",
    dependencies: ["assetId", "assetType", "className"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.489Z",
    exports: [],
  },
  "dev-wrapped-component": {
    id: "dev-wrapped-component",
    name: "WrappedComponent",
    filePath: "/components/dev/withComponentMetadata.tsx",
    startLine: 16,
    endLine: 40,
    category: ComponentCategory.UI,
    description: "WrappedComponent component",
    dependencies: ["props"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.493Z",
    exports: [],
  },
  "dev-component-wrapper": {
    id: "dev-component-wrapper",
    name: "ComponentWrapper",
    filePath: "/components/dev/withComponentMetadata.tsx",
    startLine: 50,
    endLine: 80,
    category: ComponentCategory.LAYOUT,
    description: "ComponentWrapper component",
    dependencies: ["componentId", "metadata", "children", "className"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.493Z",
    exports: [],
  },
  "visual-dev-mode-panel": {
    id: "visual-dev-mode-panel",
    name: "VisualDevModePanel",
    filePath: "/components/dev/VisualDevMode.tsx",
    startLine: 14,
    endLine: 328,
    category: ComponentCategory.UI,
    description: "VisualDevModePanel component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.495Z",
    exports: [],
  },
  "dev-component-overlay": {
    id: "dev-component-overlay",
    name: "ComponentOverlay",
    filePath: "/components/dev/ComponentOverlay.tsx",
    startLine: 13,
    endLine: 121,
    category: ComponentCategory.UI,
    description: "ComponentOverlay component",
    dependencies: ["componentId", "metadata", "children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.497Z",
    exports: [],
  },
  "dashboard-layout": {
    id: "dashboard-layout",
    name: "DashboardLayout",
    filePath: "/components/dashboard/DashboardLayout.tsx",
    startLine: 9,
    endLine: 20,
    category: ComponentCategory.LAYOUT,
    description: "DashboardLayout component",
    dependencies: ["children"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.498Z",
    exports: [],
  },
  "beneficiaries-beneficiary-photo-input": {
    id: "beneficiaries-beneficiary-photo-input",
    name: "BeneficiaryPhotoInput",
    filePath: "/components/beneficiaries/BeneficiaryPhotoInput.tsx",
    startLine: 20,
    endLine: 249,
    category: ComponentCategory.INPUT,
    description: "BeneficiaryPhotoInput component",
    dependencies: ["value", "onChange", "name", "isInvalid", "errorMessage"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.500Z",
    exports: [],
  },
  "beneficiaries-beneficiary-list": {
    id: "beneficiaries-beneficiary-list",
    name: "BeneficiaryList",
    filePath: "/components/beneficiaries/BeneficiaryList.tsx",
    startLine: 52,
    endLine: 377,
    category: ComponentCategory.DATA_DISPLAY,
    description: "BeneficiaryList component",
    dependencies: [
      "beneficiaries",
      "total",
      "page",
      "pageSize",
      "loading",
      "onPageChange",
      "onPageSizeChange",
      "onSearch",
      "onFilterChange",
      "onEdit",
      "onDelete",
      "onView",
    ],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.503Z",
    exports: [],
  },
  "beneficiaries-beneficiary-form": {
    id: "beneficiaries-beneficiary-form",
    name: "BeneficiaryForm",
    filePath: "/components/beneficiaries/BeneficiaryForm.tsx",
    startLine: 34,
    endLine: 401,
    category: ComponentCategory.INPUT,
    description: "BeneficiaryForm component",
    dependencies: ["initialData", "onSubmit", "onCancel", "loading", "mode"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.506Z",
    exports: [],
  },
  "beneficiaries-beneficiary-card": {
    id: "beneficiaries-beneficiary-card",
    name: "BeneficiaryCard",
    filePath: "/components/beneficiaries/BeneficiaryCard.tsx",
    startLine: 35,
    endLine: 228,
    category: ComponentCategory.DATA_DISPLAY,
    description: "BeneficiaryCard component",
    dependencies: ["beneficiary", "onEdit", "onDelete", "onView"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.509Z",
    exports: [],
  },
  "auth-protected-route": {
    id: "auth-protected-route",
    name: "ProtectedRoute",
    filePath: "/components/auth/ProtectedRoute.tsx",
    startLine: 14,
    endLine: 66,
    category: ComponentCategory.AUTHENTICATION,
    description: "ProtectedRoute component",
    dependencies: ["children", "requireOnboarding"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.510Z",
    exports: [],
  },
  "auth-google-sign-in-button": {
    id: "auth-google-sign-in-button",
    name: "GoogleSignInButton",
    filePath: "/components/auth/GoogleSignInButton.tsx",
    startLine: 10,
    endLine: 43,
    category: ComponentCategory.INPUT,
    description: "GoogleSignInButton component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.511Z",
    exports: [],
  },
  "auth-github-sign-in-button": {
    id: "auth-github-sign-in-button",
    name: "GithubSignInButton",
    filePath: "/components/auth/GithubSignInButton.tsx",
    startLine: 6,
    endLine: 32,
    category: ComponentCategory.INPUT,
    description: "GithubSignInButton component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.511Z",
    exports: [],
  },
  "auth-email-signup-form": {
    id: "auth-email-signup-form",
    name: "EmailSignupForm",
    filePath: "/components/auth/EmailSignupForm.tsx",
    startLine: 9,
    endLine: 189,
    category: ComponentCategory.INPUT,
    description: "EmailSignupForm component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.513Z",
    exports: [],
  },
  "auth-email-login-form": {
    id: "auth-email-login-form",
    name: "EmailLoginForm",
    filePath: "/components/auth/EmailLoginForm.tsx",
    startLine: 9,
    endLine: 110,
    category: ComponentCategory.INPUT,
    description: "EmailLoginForm component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.514Z",
    exports: [],
  },
  "auth-apple-sign-in-button": {
    id: "auth-apple-sign-in-button",
    name: "AppleSignInButton",
    filePath: "/components/auth/AppleSignInButton.tsx",
    startLine: 5,
    endLine: 28,
    category: ComponentCategory.INPUT,
    description: "AppleSignInButton component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.514Z",
    exports: [],
  },
  "will-client": {
    id: "will-client",
    name: "WillClient",
    filePath: "/app/(dashboard)/will/WillClient.tsx",
    startLine: 17,
    endLine: 258,
    category: ComponentCategory.BUSINESS,
    description: "WillClient component",
    dependencies: ["user"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.516Z",
    exports: [],
  },
  "beneficiaries-page": {
    id: "beneficiaries-page",
    name: "BeneficiariesPage",
    filePath: "/app/(dashboard)/beneficiaries/page.tsx",
    startLine: 26,
    endLine: 339,
    category: ComponentCategory.UI,
    description: "BeneficiariesPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.517Z",
    exports: [],
  },
  "assets-page": {
    id: "assets-page",
    name: "AssetsPage",
    filePath: "/app/(dashboard)/assets/page.tsx",
    startLine: 39,
    endLine: 539,
    category: ComponentCategory.BUSINESS,
    description: "AssetsPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.520Z",
    exports: [],
  },
  "dashboard-page": {
    id: "dashboard-page",
    name: "DashboardPage",
    filePath: "/app/(dashboard)/dashboard/page.tsx",
    startLine: 8,
    endLine: 10,
    category: ComponentCategory.UI,
    description: "DashboardPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.522Z",
    exports: [],
  },
  "dashboard-client": {
    id: "dashboard-client",
    name: "DashboardClient",
    filePath: "/app/(dashboard)/dashboard/DashboardClient.tsx",
    startLine: 44,
    endLine: 446,
    category: ComponentCategory.UI,
    description: "DashboardClient component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.524Z",
    exports: [],
  },
  "signup-page": {
    id: "signup-page",
    name: "SignupPage",
    filePath: "/app/(auth)/signup/page.tsx",
    startLine: 16,
    endLine: 372,
    category: ComponentCategory.AUTHENTICATION,
    description: "SignupPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.526Z",
    exports: [],
  },
  "onboarding-page": {
    id: "onboarding-page",
    name: "OnboardingPage",
    filePath: "/app/(auth)/onboarding/page.tsx",
    startLine: 55,
    endLine: 475,
    category: ComponentCategory.AUTHENTICATION,
    description: "OnboardingPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.530Z",
    exports: [],
  },
  "login-page": {
    id: "login-page",
    name: "LoginPage",
    filePath: "/app/(auth)/login/page.tsx",
    startLine: 22,
    endLine: 223,
    category: ComponentCategory.AUTHENTICATION,
    description: "LoginPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.531Z",
    exports: [],
  },
  "add-beneficiary-page": {
    id: "add-beneficiary-page",
    name: "AddBeneficiaryPage",
    filePath: "/app/(dashboard)/beneficiaries/add/page.tsx",
    startLine: 13,
    endLine: 95,
    category: ComponentCategory.BUSINESS,
    description: "AddBeneficiaryPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.534Z",
    exports: [],
  },
  "add-asset-v2page": {
    id: "add-asset-v2page",
    name: "AddAssetV2Page",
    filePath: "/app/(dashboard)/assets/add/page.tsx",
    startLine: 62,
    endLine: 1166,
    category: ComponentCategory.BUSINESS,
    description: "AddAssetV2Page component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.559Z",
    exports: [],
  },
  "components-verification-step": {
    id: "components-verification-step",
    name: "VerificationStep",
    filePath: "/app/(auth)/onboarding/components/VerificationStep.tsx",
    startLine: 30,
    endLine: 534,
    category: ComponentCategory.AUTHENTICATION,
    description: "VerificationStep component",
    dependencies: ["onComplete", "onBack", "loading"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.564Z",
    exports: [],
  },
  "components-signature-step": {
    id: "components-signature-step",
    name: "SignatureStep",
    filePath: "/app/(auth)/onboarding/components/SignatureStep.tsx",
    startLine: 21,
    endLine: 504,
    category: ComponentCategory.AUTHENTICATION,
    description: "SignatureStep component",
    dependencies: [
      "personalInfo",
      "initialSignature",
      "onChange",
      "onComplete",
      "onBack",
      "loading",
    ],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.572Z",
    exports: [],
  },
  "components-signature-stamp": {
    id: "components-signature-stamp",
    name: "SignatureStamp",
    filePath: "/app/(auth)/onboarding/components/SignatureStamp.tsx",
    startLine: 18,
    endLine: 145,
    category: ComponentCategory.AUTHENTICATION,
    description: "SignatureStamp component",
    dependencies: [
      "signature",
      "isSigned",
      "timestamp",
      "onClick",
      "disabled",
      "userName",
      "isLoading",
    ],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.573Z",
    exports: [],
  },
  "components-personal-info-step": {
    id: "components-personal-info-step",
    name: "PersonalInfoStep",
    filePath: "/app/(auth)/onboarding/components/PersonalInfoStep.tsx",
    startLine: 54,
    endLine: 342,
    category: ComponentCategory.AUTHENTICATION,
    description: "PersonalInfoStep component",
    dependencies: [
      "initialData",
      "onChange",
      "onComplete",
      "onBack",
      "loading",
    ],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.575Z",
    exports: [],
  },
  "components-legal-consent-step": {
    id: "components-legal-consent-step",
    name: "LegalConsentStep",
    filePath: "/app/(auth)/onboarding/components/LegalConsentStep.tsx",
    startLine: 65,
    endLine: 510,
    category: ComponentCategory.AUTHENTICATION,
    description: "LegalConsentStep component",
    dependencies: [
      "signature",
      "initialConsents",
      "onChange",
      "onComplete",
      "onBack",
      "loading",
    ],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.578Z",
    exports: [],
  },
  "highlighting-component-highlighter": {
    id: "highlighting-component-highlighter",
    name: "ComponentHighlighter",
    filePath: "/components/dev/advanced/highlighting/ComponentHighlighter.tsx",
    startLine: 26,
    endLine: 327,
    category: ComponentCategory.UI,
    description: "ComponentHighlighter component",
    dependencies: [
      "enabled",
      "hoverHighlight",
      "clickHighlight",
      "showTooltip",
      "animateOnHover",
      "children",
    ],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.582Z",
    exports: [],
  },
  "highlighting-boundary-overlay": {
    id: "highlighting-boundary-overlay",
    name: "BoundaryOverlay",
    filePath: "/components/dev/advanced/highlighting/BoundaryOverlay.tsx",
    startLine: 32,
    endLine: 255,
    category: ComponentCategory.UI,
    description: "BoundaryOverlay component",
    dependencies: ["enabled", "showLabels", "showDimensions", "opacity"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.585Z",
    exports: [],
  },
  "edit-beneficiary-page": {
    id: "edit-beneficiary-page",
    name: "EditBeneficiaryPage",
    filePath: "/app/(dashboard)/beneficiaries/[id]/edit/page.tsx",
    startLine: 17,
    endLine: 146,
    category: ComponentCategory.BUSINESS,
    description: "EditBeneficiaryPage component",
    dependencies: ["params"],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.589Z",
    exports: [],
  },
  "edit-asset-page": {
    id: "edit-asset-page",
    name: "EditAssetPage",
    filePath: "/app/(dashboard)/assets/[id]/edit/page.tsx",
    startLine: 8,
    endLine: 42,
    category: ComponentCategory.BUSINESS,
    description: "EditAssetPage component",
    dependencies: [],
    variants: [],
    accessibility: {
      violations: 0,
      hasAriaLabels: false,
      hasKeyboardSupport: false,
      screenReaderFriendly: false,
    },
    performance: { complexity: "low" },
    lastUpdated: "2025-08-23T13:05:03.589Z",
    exports: [],
  },
};

export const getComponentById = (id: string) => COMPONENT_REGISTRY[id];

export const getComponentsByCategory = (category: ComponentCategory) =>
  Object.values(COMPONENT_REGISTRY).filter((c) => c.category === category);

export const getAllComponents = () => Object.values(COMPONENT_REGISTRY);

export const getComponentStats = () => ({
  total: Object.keys(COMPONENT_REGISTRY).length,
  byCategory: Object.values(COMPONENT_REGISTRY).reduce(
    (acc, comp) => {
      acc[comp.category] = (acc[comp.category] || 0) + 1;

      return acc;
    },
    {} as Record<ComponentCategory, number>,
  ),
});
